### ISSUE TITLE
Not able to send traces to s3 with jaeger-objectstorage

### ISSUE THREAD

**Issue by vaish1707** [muhammadn/jaeger-s3#78]
Hi @muhammadn ,

My use case is to use aws s3 as a storage for the traces generated from our application and Jaeger reads from it. I came across your plugin and decided to use it as storage options through grpc-plugin in jaeger.  I created a private s3 bucket which blocks al public access.

Here is my config used:
```
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-objectstorage
  labels:
    jaeger-objectstorage: s3-storage
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:latest
    options:
      log-level: debug
  storage:
    type: grpc-plugin
    grpcPlugin:
      image: ghcr.io/flitnetics/jaeger-objectstorage:latest
    options:
      grpc-storage-plugin:
        binary: /plugin/jaeger-objectstorage
        configuration-file: /plugin-config/config-example.yaml
        log-level: debug
  volumeMounts:
    - name: plugin-config
      mountPath: /plugin-config
  volumes:
    - name: plugin-config
      configMap:
        name: jaeger-objectstorage
---
apiVersion: v1
data:
  config-example.yaml: |-
    schema_config:
      configs:
      - from: 2020-05-15
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

    storage_config:
      aws:
        bucketnames: jaeger-tracing-boltdb-chunks
        endpoint: s3.<region>.amazonaws.com
        region: <region>
        access_key_id: <access key id>
        secret_access_key:<secret access key>
        insecure: false
        sse_encryption: false
        http_config:
          idle_conn_timeout: 90s
          response_header_timeout: 0s
          insecure_skip_verify: false
        s3forcepathstyle: true

      boltdb_shipper:
        active_index_directory: /tmp/loki/boltdb-shipper-active
        cache_location: /tmp/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: s3
      filesystem:
        directory: /tmp/loki/chunks

    limits_config:
      retention_period: 72h
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      # for big logs tune
      per_stream_rate_limit: 512M
      per_stream_rate_limit_burst: 1024M
      cardinality_limit: 200000
      ingestion_burst_size_mb: 1000
      ingestion_rate_mb: 10000
      max_entries_limit_per_query: 1000000
      max_label_value_length: 20480
      max_label_name_length: 10240
      max_label_names_per_series: 300

    table_manager:
      retention_deletes_enabled: true
      retention_period: 72h

    compactor:
      working_directory: /tmp/loki/boltdb-shipper-compactor
      shared_store: s3

    memberlist:
      abort_if_cluster_join_fails: false
      max_join_backoff: 1m
      max_join_retries: 10
      min_join_backoff: 1s

    distributor:
      ring:
        kvstore:
          store: memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 1m
      chunk_retain_period: 30s
kind: ConfigMap
metadata:
  name: jaeger-objectstorage
  labels:
    jaeger-objectstorage: s3-storage
```

After deploying this in k8s, these are my observations.

1.  It is creating a pod for jaeger-objectstorage and when we look at the logs, it is trying to connect to Jaeger and continuously it is printing the below message with random traceId and spanId 
`{"level":"debug","ts":1670507224.6278539,"caller":"app/span_processor.go:164","msg":"Span written to the storage by the collector","trace-id":"395c43ee584ae2ff","span-id":"395c43ee584ae2ff"}`
2. Based on the above log, the meaning is it is getting some traces and sending them to s3 storage. But no data written to s3!.
3. When I try to connect to jaeger UI and check, I'm seeing the below error message.
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/21258077/206466170-f16e8e6f-826d-44e3-884b-34473e2773e4.png">
4. After a few minutes, the jaeger-objectstorage pod is stopping by itself with an error 
`rpc error: code = Unknown desc = Error: No such container: 4992c79ade356f8aadd39cbeb0bf6aa476025c9d58eec3343925d2e6a8340602`

5. When I do a `kubectl get pods` after this, I see a lot of jaeger-objectstorage pods are evicted and one of them is completed. 

```
jaeger-objectstorage-77c7f64b67-2jl4f                    0/1     Evicted     0            2m39s
jaeger-objectstorage-77c7f64b67-2n66s                    0/1     Evicted     0            2m39s
jaeger-objectstorage-77c7f64b67-47l9z                    0/1     Evicted     0            2m42s
jaeger-objectstorage-77c7f64b67-4brl8                    0/1     Evicted     0            2m44s
jaeger-objectstorage-77c7f64b67-4j8tg                    0/1     Evicted     0            2m43s
jaeger-objectstorage-77c7f64b67-4jrll                    0/1     Evicted     0            2m45s
jaeger-objectstorage-77c7f64b67-4slp4                    0/1     Evicted     0            2m44s
jaeger-objectstorage-77c7f64b67-5p26g                    0/1     Evicted     0            2m43s
jaeger-objectstorage-77c7f64b67-79h2t                    0/1     Evicted     0            2m39s
jaeger-objectstorage-77c7f64b67-79qhd                    0/1     Evicted     0            2m45s
jaeger-objectstorage-77c7f64b67-7w4kj                    0/1     Evicted     0            2m42s
jaeger-objectstorage-77c7f64b67-897n6                    0/1     Completed   0            7m27s
jaeger-objectstorage-77c7f64b67-8sttq                    0/1     Evicted     0            2m43s
jaeger-objectstorage-77c7f64b67-8zkcj                    0/1     Evicted     0            2m44s
jaeger-objectstorage-77c7f64b67-9755l                    0/1     Evicted     0            2m43s
jaeger-objectstorage-77c7f64b67-9ck4h                    0/1     Evicted     0            2m45s
jaeger-objectstorage-77c7f64b67-9cq5q                    0/1     Evicted     0            2m45s
jaeger-objectstorage-77c7f64b67-9w7k4                    0/1     Evicted     0            2m40s
jaeger-objectstorage-77c7f64b67-bw4xr                    0/1     Evicted     0            2m38s
jaeger-objectstorage-77c7f64b67-c54pn                    0/1     Evicted     0            2m41s
jaeger-objectstorage-77c7f64b67-d54cq                    0/1     Evicted     0            2m42s
jaeger-objectstorage-77c7f64b67-ff5n2                    0/1     Evicted     0            2m38s
jaeger-objectstorage-77c7f64b67-gds5t                    1/1     Running     0            2m38s
jaeger-objectstorage-77c7f64b67-gjtc5                    0/1     Evicted     0            2m44s
jaeger-objectstorage-77c7f64b67-gqwfp                    0/1     Evicted     0            2m41s
jaeger-objectstorage-77c7f64b67-hwcpx                    0/1     Evicted     0            2m45s
jaeger-objectstorage-77c7f64b67-jdr69                    0/1     Evicted     0            2m41s
jaeger-objectstorage-77c7f64b67-jqm5l                    0/1     Evicted     0            2m44s
jaeger-objectstorage-77c7f64b67-k4xl5                    0/1     Evicted     0            2m45s
jaeger-objectstorage-77c7f64b67-l7wbq                    0/1     Evicted     0            2m45s
jaeger-objectstorage-77c7f64b67-lwmpg                    0/1     Evicted     0            2m44s
jaeger-objectstorage-77c7f64b67-m82vz                    0/1     Evicted     0            2m45s
jaeger-objectstorage-77c7f64b67-m8pvp                    0/1     Evicted     0            2m42s
jaeger-objectstorage-77c7f64b67-mw6h5                    0/1     Evicted     0            2m39s
jaeger-objectstorage-77c7f64b67-p99q4                    0/1     Evicted     0            2m41s
jaeger-objectstorage-77c7f64b67-pbctx                    0/1     Evicted     0            2m40s
jaeger-objectstorage-77c7f64b67-rkmln                    0/1     Evicted     0            2m40s
jaeger-objectstorage-77c7f64b67-shbgd                    0/1     Evicted     0            2m44s
jaeger-objectstorage-77c7f64b67-sv6mt                    0/1     Evicted     0            2m38s
jaeger-objectstorage-77c7f64b67-t7z5v                    0/1     Evicted     0            2m40s
jaeger-objectstorage-77c7f64b67-thc92                    0/1     Evicted     0            2m43s
jaeger-objectstorage-77c7f64b67-wmv9v                    0/1     Evicted     0            2m44s
jaeger-objectstorage-77c7f64b67-xjjfp                    0/1     Evicted     0            2m44s
jaeger-objectstorage-77c7f64b67-zjzrd                    0/1     Evicted     0            2m42s
jaeger-objectstorage-77c7f64b67-zsg42                    0/1     Evicted     0            2m38s
jaeger-objectstorage-77c7f64b67-zzpwq                    0/1     Evicted     0            2m39s

```

I'm really not sure whats going wrong over here.. Is it possible to put up your config here? I saw in another issue https://github.com/flitnetics/jaeger-objectstorage/issues/77 of yours you mentioned you are already running this plugin in production. Just want to get your help to get this working!

**Comment by muhammadn** [comment]
@vaish1707 Never run `allinOne` mode on production, the massive amount of data that is going to be ingested will cause pods to to use massive amount of memory. 

The error you got in jaeger-UI as you say it is: **no data is in s3**. It will take some time to see the data (with the `/fake` folder)

If you run in production mode, agents, collectors and store are in separated pods instead having all of it in one "jaeger-objectstorage" pod.

Try this:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: grpc-plugin
    grpcPlugin:
      image: ghcr.io/flitnetics/jaeger-objectstorage:latest
    options:
      grpc-storage-plugin:
        binary: /plugin/jaeger-objectstorage
        configuration-file: /plugin-config/config-example.yaml
        log-level: debug
```

rest should be the same..
