### ISSUE TITLE
Too many small files written to object storage

### ISSUE THREAD

**Issue by Antaxify** [muhammadn/jaeger-s3#79]
Hi,

I gave this plugin a try, however I noticed it's writing lot's and lot's of small files (~900B each)to the object storage (GCS). Based on https://github.com/grafana/loki/issues/7851, I tried to increase `chunk_target_size`, `chunk_retain_period`, `chunk_idle_period`, but no luck so far. In our (quite large) setup, the plugin writes about 12 million files / hour.

Does the plugin write 1 chunk / span? Is it intended that it writes so many files or did I misconfigure it? Below is the config I use. Thanks for the help! :)

```
---
apiVersion: v1
data:
  plugin-config.yaml: |-
    schema_config:
      configs:
        - from: 2020-07-01
          store: boltdb-shipper
          object_store: gcs
          schema: v11
          index:
            prefix: index_
            period: 24h
          row_shards: 32

    storage_config:
      gcs:
        bucket_name: my-bucket-name
      boltdb_shipper:
        active_index_directory: /tmp/loki/boltdb-shipper-active
        cache_location: /tmp/loki/boltdb-shipper-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: gcs
      filesystem:
        directory: /tmp/loki/chunks

    compactor:
      working_directory: /tmp/loki/boltdb-shipper-compactor
      shared_store: gcs

    limits_config:
      max_streams_per_user: 0             # disable limit
      max_global_streams_per_user: 0      # disable limit
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    memberlist:
      abort_if_cluster_join_fails: false
      max_join_backoff: 1m
      max_join_retries: 10
      min_join_backoff: 1s

    distributor:
      ring:
        kvstore:
          store: memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 10m
      chunk_retain_period: 60s
      chunk_target_size: 5572864
kind: ConfigMap
metadata:
  name: plugin-config
```
  
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-gcs
spec:
  serviceAccount: jaeger
  strategy: production
  collector:
    minReplicas: 6
    maxReplicas: 12
  storage:
    type: grpc-plugin
    grpcPlugin:
      image: ghcr.io/flitnetics/jaeger-objectstorage:latest
    options:
      grpc-storage-plugin:
        binary: /plugin/jaeger-objectstorage
        configuration-file: /plugin-config/plugin-config.yaml
        log-level: debug
  volumeMounts:
    - name: config-volume
      mountPath: /plugin-config
  volumes:
    - name: config-volume
      configMap:
        name: plugin-config
```
